# Generated by Django 5.1.3 on 2024-11-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiReactApp', '0002_remove_cliente_correo_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='disponible',
        ),
        migrations.AddField(
            model_name='libro',
            name='categoria',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
